services:
  deezer:
    restart: unless-stopped
    image: pkill/deezer-ympd:latest
    build: .
    ports:
      - 127.0.0.1:8039:80
      - 6600:6600
    volumes:
      # MPD Library
      - ./mpd:/var/lib/mpd
      # MPD Music Library base path
      - /data/music/deezer-downloader:/mnt/deezer-downloader
      #- /data/nyx/Soundtracks:/mnt/deezer-downloader/Soundtracks
      # Logs
      - ./log:/log/
      # Your Collection
      # - /data/my_music:/mnt/deezer-downloader/my_music
      - ./mpd.conf:/etc/mpd.conf
      # your spotify cookies
      - ./cookies.txt:/app/cookies.txt
    dns:
      - "1.1.1.1"
      - "8.8.8.8"
    environment:
      #- DEEZER_COOKIE_ARL=649fd802d70b6c3ace6f9f533a9dcc32bdbe384c433d2c545b4f6827456c6b8f5205b72376768d1dd23972b90f18ee27dd7833250f71339f67afc2ed2166fda3f0156994ac1244797ea63183af44da884a5d396b083e748a1bf24e8c82507510
      #- DEEZER_COOKIE_ARL=f0fdc6f4bda9fbb7f0b3e5ba395a0cb9308f8f170651507ff28e9af32478fdc5ead94b0ca940dc509d5b348e0fbb9f634311d84fbc5a86f0e1c8680750f6b08c9667248075e62a5b9ea223a48170d02bb5abbd880f743e339adac5a892f7641f
      #- DEEZER_COOKIE_ARL=935356b0d7efe593b067f773742560bbe2064a42389ba8f144d8596821d54e9ec35afd9036f9b81a2e3803ccbd0f047e34a1d0920b5c5c64b99201c85a31ceaa197783ce23e17ae0fd7b80dacfb921d4e19f44f1cb31dfc1dbaf1b3b06de6d42
      #- DEEZER_COOKIE_ARL=3428b500c0de1d8c11297ede30d8f8f106125969b632385492d12e303374f42b7c90d90709cc18d5e84892fc6353b1e537dfffe02d9db4fa54f828f53785d98cd9cfe9de4bddd9020be62249a0d133ed4ce772d091e802e1b9fc63ea19dc40b8
      - DEEZER_COOKIE_ARL=f0c853257f0c4a44c94f30425c24f8fd22bfccb3dd5d80cdceb87f6bb56abbd4849ea366658658629478d4c3067e11e4ed9d9b8ad9bd7e23575f902a0e5fade4ff1bd6c6119d0b83b3cb3a26b0cb7de7e3b41561fe4828f44d59b8be5b79cdd4
